<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test" tests="5" skipped="0" failures="2" errors="0" timestamp="2024-09-16T18:38:40" hostname="9a67a67c0945" time="0.203779756"><testcase name="get_user_1" classname="get_user_1" time="0.000853709"><failure message="assertion failed">thread &apos;get_user_1&apos; panicked at tests/test-runner.rs:14:66:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: &quot;No such file or directory&quot; }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
</failure></testcase><testcase name="get_user_2" classname="get_user_2" time="0.121438237"/><testcase name="add_user" classname="add_user" time="0.122580486"><failure message="assertion failed">thread &apos;add_user&apos; panicked at tests/contract_testing_logic/mod.rs:155:9:
assertion `left == right` failed
  left: 404
 right: 201
</failure></testcase><testcase name="get_user_3" classname="get_user_3" time="0.073320318"/><testcase name="get_user_4" classname="get_user_4" time="0.072998917"/>
</testsuite>